using System.ComponentModel;
using System.Globalization;

namespace StorageScanner.Core;

/// <summary>Traductions de l'interface (français, anglais, espagnol, allemand), modifiables à chaud.
/// En XAML : <c>{ui:L clé}</c> ; en C# : <c>Loc.T("clé")</c> ou <c>Loc.F("clé", arguments)</c>.
/// Les formats de nombres et de dates suivent toujours les réglages régionaux de Windows.</summary>
public sealed class Loc : INotifyPropertyChanged
{
    public static readonly string[] Languages = ["fr", "en", "es", "de"];
    public static Loc Instance { get; } = new();

    private int _index;

    /// <summary>Code de la langue active (« fr », « en », « es », « de »).</summary>
    public static string Current => Languages[Instance._index];

    public static event Action? Changed;
    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>Langue de Windows si elle est disponible, sinon anglais.</summary>
    public static string SystemDefault =>
        Array.IndexOf(Languages, CultureInfo.CurrentUICulture.TwoLetterISOLanguageName) >= 0
            ? CultureInfo.CurrentUICulture.TwoLetterISOLanguageName : "en";

    public static void Set(string lang)
    {
        int i = Array.IndexOf(Languages, lang);
        if (i < 0 || i == Instance._index && s_initialized) return;
        s_initialized = true;
        Instance._index = i;
        Instance.PropertyChanged?.Invoke(Instance, new PropertyChangedEventArgs("Item[]"));
        Changed?.Invoke();
    }

    private static bool s_initialized;

    /// <summary>Indexeur utilisé par les liaisons XAML.</summary>
    public string this[string key] => T(key);

    public static string T(string key) =>
        Table.TryGetValue(key, out var v) ? v[Instance._index] : key;

    public static string F(string key, params object?[] args) =>
        string.Format(CultureInfo.CurrentCulture, T(key), args);

    // Ordre des colonnes : français, anglais, espagnol, allemand
    private static readonly Dictionary<string, string[]> Table = new()
    {
        // ---- Fenêtre, barre de commande ----
        ["language"] = ["Langue", "Language", "Idioma", "Sprache"],
        ["minimize"] = ["Réduire", "Minimize", "Minimizar", "Minimieren"],
        ["maximize"] = ["Agrandir", "Maximize", "Maximizar", "Maximieren"],
        ["restore"] = ["Restaurer", "Restore", "Restaurar", "Wiederherstellen"],
        ["close"] = ["Fermer", "Close", "Cerrar", "Schließen"],
        ["adminMode"] = ["Mode administrateur", "Administrator mode", "Modo administrador", "Administratormodus"],
        ["adminModeTip"] = ["Relancer en administrateur pour analyser aussi les dossiers protégés (invite UAC)",
            "Restart as administrator to also scan protected folders (UAC prompt)",
            "Reiniciar como administrador para analizar también las carpetas protegidas (aviso UAC)",
            "Als Administrator neu starten, um auch geschützte Ordner zu analysieren (UAC-Abfrage)"],
        ["adminBadge"] = ["Administrateur", "Administrator", "Administrador", "Administrator"],
        ["adminBadgeTip"] = ["L'application tourne avec les droits administrateur. Les lecteurs réseau de votre session y sont reconnectés automatiquement.",
            "The application is running with administrator rights. Your session's network drives are reconnected automatically.",
            "La aplicación se ejecuta con derechos de administrador. Las unidades de red de su sesión se vuelven a conectar automáticamente.",
            "Die Anwendung läuft mit Administratorrechten. Die Netzlaufwerke Ihrer Sitzung werden automatisch wieder verbunden."],
        ["themeToLight"] = ["Passer au thème clair", "Switch to light theme", "Cambiar al tema claro", "Zum hellen Design wechseln"],
        ["themeToDark"] = ["Passer au thème sombre", "Switch to dark theme", "Cambiar al tema oscuro", "Zum dunklen Design wechseln"],
        ["pathPlaceholder"] = ["Dossier local ou chemin réseau — ex.  D:\\Données   ·   \\\\serveur\\partage\\dossier   ·   \\\\serveur (tous ses partages)",
            "Local folder or network path — e.g.  D:\\Data   ·   \\\\server\\share\\folder   ·   \\\\server (all its shares)",
            "Carpeta local o ruta de red — p. ej.  D:\\Datos   ·   \\\\servidor\\recurso\\carpeta   ·   \\\\servidor (todos sus recursos)",
            "Lokaler Ordner oder Netzwerkpfad — z. B.  D:\\Daten   ·   \\\\server\\freigabe\\ordner   ·   \\\\server (alle Freigaben)"],
        ["recentTip"] = ["Analyses récentes", "Recent scans", "Análisis recientes", "Letzte Analysen"],
        ["recentUpper"] = ["ANALYSES RÉCENTES", "RECENT SCANS", "ANÁLISIS RECIENTES", "LETZTE ANALYSEN"],
        ["browse"] = ["Parcourir", "Browse", "Examinar", "Durchsuchen"],
        ["browseTip"] = ["Choisir un dossier", "Choose a folder", "Elegir una carpeta", "Ordner auswählen"],
        ["scan"] = ["Analyser", "Scan", "Analizar", "Analysieren"],
        ["scanTip"] = ["Lancer l'analyse (Entrée)", "Start the scan (Enter)", "Iniciar el análisis (Intro)", "Analyse starten (Eingabe)"],
        ["stop"] = ["Arrêter", "Stop", "Detener", "Stoppen"],
        ["export"] = ["Exporter", "Export", "Exportar", "Exportieren"],
        ["exportTip"] = ["Exporter l'onglet affiché au format CSV (Excel)", "Export the current tab as CSV (Excel)",
            "Exportar la pestaña actual en CSV (Excel)", "Aktuelle Registerkarte als CSV exportieren (Excel)"],
        ["toggleTreemapTip"] = ["Afficher / masquer la carte des volumes", "Show / hide the volume map", "Mostrar / ocultar el mapa de volúmenes",
            "Volumenkarte ein-/ausblenden"],
        ["settings"] = ["Paramètres", "Settings", "Configuración", "Einstellungen"],
        ["homeTip"] = ["Revenir à l'accueil", "Back to home", "Volver al inicio", "Zur Startseite"],

        // ---- Paramètres ----
        ["settingsTitle"] = ["Paramètres d'analyse", "Scan settings", "Configuración del análisis", "Analyseeinstellungen"],
        ["optThreads"] = ["Threads d'analyse", "Scan threads", "Hilos de análisis", "Analyse-Threads"],
        ["optThreadsHint"] = ["Réseau : 16 à 32 · disque local : 8 à 16", "Network: 16 to 32 · local disk: 8 to 16",
            "Red: 16 a 32 · disco local: 8 a 16", "Netzwerk: 16 bis 32 · lokales Laufwerk: 8 bis 16"],
        ["optDupMin"] = ["Doublons : taille min. (Mo)", "Duplicates: min. size (MB)", "Duplicados: tamaño mín. (MB)", "Duplikate: Mindestgröße (MB)"],
        ["optDupMinHint"] = ["Fichiers retenus pour la comparaison, appliqué à la prochaine analyse",
            "Files kept for comparison, applied to the next scan", "Archivos considerados para la comparación, se aplica en el próximo análisis",
            "Für den Vergleich berücksichtigte Dateien, gilt ab der nächsten Analyse"],
        ["optDupThreads"] = ["Doublons : lectures parallèles", "Duplicates: parallel reads", "Duplicados: lecturas en paralelo", "Duplikate: parallele Lesevorgänge"],
        ["optSaved"] = ["Réglages mémorisés pour les prochaines fois", "Settings are remembered for next time",
            "La configuración se guarda para la próxima vez", "Einstellungen werden für das nächste Mal gespeichert"],
        ["shortcuts"] = ["Raccourcis clavier", "Keyboard shortcuts", "Atajos de teclado", "Tastenkürzel"],
        ["kEnterF5"] = ["Entrée / F5", "Enter / F5", "Intro / F5", "Eingabe / F5"],
        ["kEsc"] = ["Échap", "Esc", "Esc", "Esc"],
        ["kCtrlF"] = ["Ctrl+F", "Ctrl+F", "Ctrl+F", "Strg+F"],
        ["kCtrlL"] = ["Ctrl+L", "Ctrl+L", "Ctrl+L", "Strg+L"],
        ["kCtrlO"] = ["Ctrl+O", "Ctrl+O", "Ctrl+O", "Strg+O"],
        ["kCtrlE"] = ["Ctrl+E", "Ctrl+E", "Ctrl+E", "Strg+E"],
        ["kCtrl17"] = ["Ctrl+1 … 7", "Ctrl+1 … 7", "Ctrl+1 … 7", "Strg+1 … 7"],
        ["kDrag"] = ["Glisser", "Drag", "Arrastrar", "Ziehen"],
        ["kbScan"] = ["Analyser / relancer l'analyse", "Scan / rescan", "Analizar / volver a analizar", "Analysieren / erneut analysieren"],
        ["kbStop"] = ["Arrêter l'analyse en cours", "Stop the current scan", "Detener el análisis en curso", "Laufende Analyse stoppen"],
        ["kbSearch"] = ["Rechercher un dossier", "Find a folder", "Buscar una carpeta", "Ordner suchen"],
        ["kbPath"] = ["Saisir un chemin", "Type a path", "Escribir una ruta", "Pfad eingeben"],
        ["kbBrowse"] = ["Parcourir…", "Browse…", "Examinar…", "Durchsuchen…"],
        ["kbExport"] = ["Exporter l'onglet en CSV", "Export the tab as CSV", "Exportar la pestaña en CSV", "Registerkarte als CSV exportieren"],
        ["kbTabs"] = ["Changer d'onglet", "Switch tab", "Cambiar de pestaña", "Registerkarte wechseln"],
        ["kbDrag"] = ["Déposer un dossier pour l'analyser", "Drop a folder to scan it", "Soltar una carpeta para analizarla",
            "Ordner ablegen, um ihn zu analysieren"],

        // ---- Indicateurs ----
        ["kpiSize"] = ["Espace occupé", "Space used", "Espacio ocupado", "Belegter Speicher"],
        ["files"] = ["Fichiers", "Files", "Archivos", "Dateien"],
        ["folders"] = ["Dossiers", "Folders", "Carpetas", "Ordner"],
        ["kpiDuration"] = ["Durée de l'analyse", "Scan duration", "Duración del análisis", "Analysedauer"],
        ["inaccessibleFolders"] = ["Dossiers inaccessibles", "Inaccessible folders", "Carpetas inaccesibles", "Nicht zugängliche Ordner"],
        ["kpiSuspects"] = ["Fichiers suspects", "Suspicious files", "Archivos sospechosos", "Verdächtige Dateien"],
        ["kpiSuspectsTip"] = ["Fichiers présentant des signes de logiciel malveillant — cliquer pour les voir",
            "Files showing signs of malware — click to see them", "Archivos con indicios de software malicioso — haga clic para verlos",
            "Dateien mit Anzeichen von Schadsoftware — zum Anzeigen klicken"],

        // ---- Accueil / analyse ----
        ["welcomeTitle"] = ["Où est passé votre espace disque ?", "Where did your disk space go?", "¿Adónde ha ido su espacio en disco?",
            "Wo ist Ihr Speicherplatz geblieben?"],
        ["welcomeText"] = ["Saisissez un dossier ou un partage réseau ci-dessus, ou choisissez directement un lecteur :",
            "Enter a folder or network share above, or pick a drive directly:",
            "Escriba una carpeta o un recurso de red arriba, o elija directamente una unidad:",
            "Geben Sie oben einen Ordner oder eine Netzwerkfreigabe ein oder wählen Sie direkt ein Laufwerk:"],
        ["tipBefore"] = ["Astuce : pour un partage réseau volumineux, augmentez le nombre de threads dans les paramètres",
            "Tip: for a large network share, increase the number of threads in the settings",
            "Consejo: para un recurso de red voluminoso, aumente el número de hilos en la configuración",
            "Tipp: Erhöhen Sie bei einer großen Netzwerkfreigabe die Anzahl der Threads in den Einstellungen"],
        ["tipAfter"] = ["pour accélérer l'analyse.", "to speed up the scan.", "para acelerar el análisis.", "– so geht die Analyse schneller."],
        ["scanning"] = ["Analyse en cours…", "Scanning…", "Analizando…", "Analyse läuft…"],
        ["stopScan"] = ["Arrêter l'analyse", "Stop the scan", "Detener el análisis", "Analyse stoppen"],

        // ---- Onglets et colonnes ----
        ["tabTree"] = ["Arborescence", "Tree", "Árbol", "Verzeichnisbaum"],
        ["tabBigFiles"] = ["Gros fichiers", "Largest files", "Archivos grandes", "Größte Dateien"],
        ["tabTypes"] = ["Types de fichiers", "File types", "Tipos de archivo", "Dateitypen"],
        ["tabDuplicates"] = ["Doublons", "Duplicates", "Duplicados", "Duplikate"],
        ["tabStale"] = ["Dossiers inactifs", "Inactive folders", "Carpetas inactivas", "Inaktive Ordner"],
        ["sortBy"] = ["Trier par", "Sort by", "Ordenar por", "Sortieren nach"],
        ["sortName"] = ["Nom (ordre Windows)", "Name (Windows order)", "Nombre (orden de Windows)", "Name (Windows-Reihenfolge)"],
        ["name"] = ["Nom", "Name", "Nombre", "Name"],
        ["size"] = ["Taille", "Size", "Tamaño", "Größe"],
        ["date"] = ["Date", "Date", "Fecha", "Datum"],
        ["pctParent"] = ["% du parent", "% of parent", "% del padre", "% vom übergeordneten"],
        ["modified"] = ["Modifié le", "Modified", "Modificado", "Geändert am"],
        ["lastModified"] = ["Dernière modification", "Last modified", "Última modificación", "Letzte Änderung"],
        ["type"] = ["Type", "Type", "Tipo", "Typ"],
        ["extension"] = ["Extension", "Extension", "Extensión", "Erweiterung"],
        ["location"] = ["Emplacement", "Location", "Ubicación", "Speicherort"],
        ["path"] = ["Chemin", "Path", "Ruta", "Pfad"],
        ["error"] = ["Erreur", "Error", "Error", "Fehler"],
        ["file"] = ["Fichier", "File", "Archivo", "Datei"],
        ["folder"] = ["Dossier", "Folder", "Carpeta", "Ordner"],
        ["level"] = ["Niveau", "Level", "Nivel", "Stufe"],
        ["why"] = ["Pourquoi ?", "Why?", "¿Por qué?", "Warum?"],
        ["antivirus"] = ["Antivirus", "Antivirus", "Antivirus", "Virenschutz"],
        ["avgSize"] = ["Taille moyenne", "Average size", "Tamaño medio", "Durchschnittsgröße"],
        ["shareOfTotal"] = ["Part du total", "Share of total", "Parte del total", "Anteil am Gesamt"],
        ["unitSize"] = ["Taille unitaire", "Unit size", "Tamaño unitario", "Einzelgröße"],
        ["copies"] = ["Copies", "Copies", "Copias", "Kopien"],
        ["recoverable"] = ["Espace récupérable", "Recoverable space", "Espacio recuperable", "Freizugebender Speicher"],
        ["sha256"] = ["Empreinte SHA-256", "SHA-256 hash", "Huella SHA-256", "SHA-256-Prüfsumme"],
        ["copyLocations"] = ["Emplacements des copies", "Copy locations", "Ubicaciones de las copias", "Speicherorte der Kopien"],
        ["treeHint"] = ["Double-clic ou ← → pour déplier · clic droit pour plus d'actions",
            "Double-click or ← → to expand · right-click for more actions",
            "Doble clic o ← → para desplegar · clic derecho para más acciones",
            "Doppelklick oder ← → zum Aufklappen · Rechtsklick für weitere Aktionen"],
        ["searchPlaceholder"] = ["Rechercher un dossier (Ctrl+F)", "Find a folder (Ctrl+F)", "Buscar una carpeta (Ctrl+F)", "Ordner suchen (Strg+F)"],
        ["prevTip"] = ["Précédent (Maj+Entrée)", "Previous (Shift+Enter)", "Anterior (Mayús+Intro)", "Zurück (Umschalt+Eingabe)"],
        ["nextTip"] = ["Suivant (Entrée)", "Next (Enter)", "Siguiente (Intro)", "Weiter (Eingabe)"],
        ["findDuplicates"] = ["Rechercher les doublons", "Find duplicates", "Buscar duplicados", "Duplikate suchen"],
        ["cancelSearch"] = ["Annuler la recherche", "Cancel the search", "Cancelar la búsqueda", "Suche abbrechen"],
        ["dupMethod"] = ["Comparaison par taille, puis empreinte partielle (début + fin), puis SHA-256 complet",
            "Compared by size, then partial hash (start + end), then full SHA-256",
            "Comparación por tamaño, luego huella parcial (inicio + fin), luego SHA-256 completo",
            "Vergleich nach Größe, dann Teil-Prüfsumme (Anfang + Ende), dann vollständige SHA-256"],
        ["suspectsBannerTitle"] = ["ATTENTION : FICHIERS POTENTIELLEMENT MALVEILLANTS", "WARNING: POTENTIALLY MALICIOUS FILES",
            "ATENCIÓN: ARCHIVOS POTENCIALMENTE MALICIOSOS", "ACHTUNG: MÖGLICHERWEISE SCHÄDLICHE DATEIEN"],
        ["suspectsBannerText"] = ["N'ouvrez pas ces fichiers. En cas de menace confirmée, prévenez votre service informatique.",
            "Do not open these files. If a threat is confirmed, notify your IT department.",
            "No abra estos archivos. Si se confirma una amenaza, avise a su departamento de informática.",
            "Öffnen Sie diese Dateien nicht. Bei einer bestätigten Bedrohung informieren Sie Ihre IT-Abteilung."],
        ["checkAll"] = ["Tout vérifier avec l'antivirus", "Check all with the antivirus", "Comprobar todo con el antivirus", "Alle mit dem Virenschutz prüfen"],
        ["checkSelected"] = ["Vérifier le fichier sélectionné", "Check the selected file", "Comprobar el archivo seleccionado", "Ausgewählte Datei prüfen"],
        ["stopCheck"] = ["Arrêter la vérification", "Stop checking", "Detener la comprobación", "Prüfung stoppen"],
        ["noSuspectsTitle"] = ["Aucun fichier suspect détecté", "No suspicious files detected", "No se detectaron archivos sospechosos",
            "Keine verdächtigen Dateien gefunden"],
        ["noSuspectsText"] = ["Aucun des indices habituels de logiciel malveillant n'a été trouvé. Cela ne remplace pas votre antivirus.",
            "None of the usual signs of malware were found. This does not replace your antivirus.",
            "No se encontró ninguno de los indicios habituales de software malicioso. Esto no sustituye a su antivirus.",
            "Keines der üblichen Anzeichen von Schadsoftware wurde gefunden. Dies ersetzt nicht Ihren Virenschutz."],
        ["staleLabel"] = ["Aucun fichier modifié depuis", "No file modified for", "Ningún archivo modificado desde hace", "Keine Datei geändert seit"],
        ["years"] = ["an(s)", "year(s)", "año(s)", "Jahr(en)"],

        // ---- Menus contextuels ----
        ["openInExplorer"] = ["Ouvrir dans l'Explorateur", "Open in File Explorer", "Abrir en el Explorador", "Im Explorer öffnen"],
        ["showInExplorer"] = ["Afficher dans l'Explorateur", "Show in File Explorer", "Mostrar en el Explorador", "Im Explorer anzeigen"],
        ["copyPath"] = ["Copier le chemin", "Copy path", "Copiar la ruta", "Pfad kopieren"],
        ["properties"] = ["Propriétés", "Properties", "Propiedades", "Eigenschaften"],
        ["showInTree"] = ["Afficher dans l'arborescence", "Show in tree", "Mostrar en el árbol", "Im Verzeichnisbaum anzeigen"],
        ["zoomTreemapHere"] = ["Centrer la carte sur ce dossier", "Center the map on this folder", "Centrar el mapa en esta carpeta",
            "Karte auf diesen Ordner zentrieren"],
        ["scanThisFolder"] = ["Analyser uniquement ce dossier", "Scan only this folder", "Analizar solo esta carpeta", "Nur diesen Ordner analysieren"],
        ["checkWithAv"] = ["Vérifier avec l'antivirus", "Check with the antivirus", "Comprobar con el antivirus", "Mit dem Virenschutz prüfen"],

        // ---- Carte des volumes ----
        ["treemapTitle"] = ["Carte des volumes", "Volume map", "Mapa de volúmenes", "Volumenkarte"],
        ["up"] = ["Remonter", "Up", "Subir", "Nach oben"],
        ["upTip"] = ["Remonter d'un niveau (clic droit sur la carte)", "Up one level (right-click on the map)",
            "Subir un nivel (clic derecho en el mapa)", "Eine Ebene nach oben (Rechtsklick auf die Karte)"],
        ["root"] = ["Racine", "Root", "Raíz", "Stamm"],
        ["rootTip"] = ["Revenir au dossier analysé", "Back to the scanned folder", "Volver a la carpeta analizada", "Zurück zum analysierten Ordner"],
        ["treemapHint"] = ["Plus un bloc est grand, plus il occupe d'espace · survol : détail · clic : afficher dans l'arborescence · double-clic : zoomer · clic droit : remonter",
            "The bigger a block, the more space it uses · hover: details · click: show in tree · double-click: zoom · right-click: up",
            "Cuanto más grande es un bloque, más espacio ocupa · pasar el ratón: detalle · clic: mostrar en el árbol · doble clic: ampliar · clic derecho: subir",
            "Je größer ein Block, desto mehr Speicher belegt er · Zeigen: Details · Klick: im Baum anzeigen · Doppelklick: zoomen · Rechtsklick: nach oben"],
        ["treemapEmpty"] = ["La carte des volumes s'affichera ici après l'analyse.", "The volume map will appear here after the scan.",
            "El mapa de volúmenes aparecerá aquí después del análisis.", "Die Volumenkarte erscheint hier nach der Analyse."],
        ["treemapNoData"] = ["Aucune donnée à afficher.", "No data to display.", "No hay datos que mostrar.", "Keine Daten anzuzeigen."],
        ["treemapRootFiles"] = ["Fichiers à la racine", "Files at the root", "Archivos en la raíz", "Dateien im Stamm"],
        ["treemapOthers"] = ["Autres", "Others", "Otros", "Sonstige"],
        ["treemapSmallFiles"] = ["Autres petits fichiers dans {0}", "Other small files in {0}", "Otros archivos pequeños en {0}", "Weitere kleine Dateien in {0}"],
        ["treemapFilesIn"] = ["Fichiers dans {0}", "Files in {0}", "Archivos en {0}", "Dateien in {0}"],
        ["nFiles"] = ["{0:N0} fichier(s)", "{0:N0} file(s)", "{0:N0} archivo(s)", "{0:N0} Datei(en)"],

        // ---- Arborescence ----
        ["treeFilesRow"] = ["[{0:N0} fichier(s)]", "[{0:N0} file(s)]", "[{0:N0} archivo(s)]", "[{0:N0} Datei(en)]"],
        ["treeReparse"] = ["Jonction / lien symbolique (non parcouru)", "Junction / symbolic link (not followed)",
            "Unión / vínculo simbólico (no recorrido)", "Verbindungspunkt / symbolischer Link (nicht durchsucht)"],
        ["treeError"] = ["Dossier inaccessible : accès refusé ou erreur de lecture (voir l'onglet Erreurs)",
            "Inaccessible folder: access denied or read error (see the Errors tab)",
            "Carpeta inaccesible: acceso denegado o error de lectura (ver la pestaña Errores)",
            "Ordner nicht zugänglich: Zugriff verweigert oder Lesefehler (siehe Registerkarte Fehler)"],
        ["treeSuspects"] = ["⚠ ATTENTION : contient {0:N0} fichier(s) potentiellement malveillant(s) — voir l'onglet Suspects",
            "⚠ WARNING: contains {0:N0} potentially malicious file(s) — see the Suspicious tab",
            "⚠ ATENCIÓN: contiene {0:N0} archivo(s) potencialmente malicioso(s) — ver la pestaña Sospechosos",
            "⚠ ACHTUNG: enthält {0:N0} möglicherweise schädliche Datei(en) — siehe Registerkarte Verdächtig"],

        // ---- Lecteurs ----
        ["networkDrive"] = ["Lecteur réseau", "Network drive", "Unidad de red", "Netzlaufwerk"],
        ["localDisk"] = ["Disque local", "Local disk", "Disco local", "Lokaler Datenträger"],
        ["scanX"] = ["Analyser {0}", "Scan {0}", "Analizar {0}", "{0} analysieren"],
        ["freeOf"] = ["{0} libres sur {1}", "{0} free of {1}", "{0} libres de {1}", "{0} frei von {1}"],

        // ---- Statuts ----
        ["ready"] = ["Prêt", "Ready", "Listo", "Bereit"],
        ["adminStatus"] = ["Mode administrateur", "Administrator mode", "Modo administrador", "Administratormodus"],
        ["adminStatusBackup"] = ["Mode administrateur · lecture étendue activée (privilège de sauvegarde)",
            "Administrator mode · extended read enabled (backup privilege)",
            "Modo administrador · lectura ampliada activada (privilegio de copia de seguridad)",
            "Administratormodus · erweiterter Lesezugriff aktiv (Sicherungsrecht)"],
        ["avSearching"] = ["Recherche de l'antivirus…", "Looking for the antivirus…", "Buscando el antivirus…", "Virenschutz wird gesucht…"],
        ["avNone"] = ["Aucun antivirus en ligne de commande détecté", "No command-line antivirus detected", "No se detectó ningún antivirus de línea de comandos",
            "Kein Befehlszeilen-Virenschutz gefunden"],
        ["avBy"] = ["Vérification par : {0}", "Checked by: {0}", "Comprobación con: {0}", "Prüfung durch: {0}"],
        ["avNoneFile"] = ["Aucun antivirus utilisable en ligne de commande n'a été trouvé sur ce poste.",
            "No usable command-line antivirus was found on this computer.",
            "No se encontró ningún antivirus utilizable por línea de comandos en este equipo.",
            "Auf diesem Computer wurde kein nutzbarer Befehlszeilen-Virenschutz gefunden."],
        ["avChecking"] = ["Vérification antivirus {0}/{1} : {2}", "Antivirus check {0}/{1}: {2}", "Comprobación antivirus {0}/{1}: {2}",
            "Virenprüfung {0}/{1}: {2}"],
        ["avThreats"] = ["⚠ {0} MENACE(S) CONFIRMÉE(S) par {1} — consultez votre antivirus ou votre service informatique",
            "⚠ {0} THREAT(S) CONFIRMED by {1} — check your antivirus or contact your IT department",
            "⚠ {0} AMENAZA(S) CONFIRMADA(S) por {1} — consulte su antivirus o a su departamento de informática",
            "⚠ {0} BEDROHUNG(EN) von {1} BESTÄTIGT — prüfen Sie Ihren Virenschutz oder wenden Sie sich an Ihre IT-Abteilung"],
        ["avDone"] = ["Vérification terminée : aucune menace détectée par {0} sur {1} fichier(s)",
            "Check complete: no threat detected by {0} in {1} file(s)",
            "Comprobación terminada: {0} no detectó ninguna amenaza en {1} archivo(s)",
            "Prüfung abgeschlossen: {0} hat in {1} Datei(en) keine Bedrohung gefunden"],
        ["avNotChecked"] = ["Non vérifié", "Not checked", "No comprobado", "Nicht geprüft"],
        ["avScanning"] = ["Analyse en cours…", "Scanning…", "Analizando…", "Prüfung läuft…"],
        ["avNotFound"] = ["Fichier introuvable (déplacé ou mis en quarantaine ?)", "File not found (moved or quarantined?)",
            "Archivo no encontrado (¿movido o en cuarentena?)", "Datei nicht gefunden (verschoben oder in Quarantäne?)"],
        ["avFolderScanned"] = [" — dossier analysé : {0}", " — folder scanned: {0}", " — carpeta analizada: {0}", " — analysierter Ordner: {0}"],
        ["avInvalidPath"] = ["Chemin non valide", "Invalid path", "Ruta no válida", "Ungültiger Pfad"],
        ["avCannotStart"] = ["Impossible de lancer l'antivirus", "Unable to start the antivirus", "No se puede iniciar el antivirus",
            "Virenschutz kann nicht gestartet werden"],
        ["avInterrupted"] = ["Analyse interrompue", "Scan interrupted", "Análisis interrumpido", "Prüfung abgebrochen"],
        ["avTimeout"] = ["Délai dépassé (10 min)", "Timed out (10 min)", "Tiempo agotado (10 min)", "Zeitüberschreitung (10 Min.)"],
        ["avThreat"] = ["MENACE DÉTECTÉE par {0}", "THREAT DETECTED by {0}", "AMENAZA DETECTADA por {0}", "BEDROHUNG ERKANNT durch {0}"],
        ["avClean"] = ["Aucune menace ({0})", "No threat ({0})", "Ninguna amenaza ({0})", "Keine Bedrohung ({0})"],
        ["avUnexpected"] = ["Réponse inattendue de {0} (code {1})", "Unexpected response from {0} (code {1})",
            "Respuesta inesperada de {0} (código {1})", "Unerwartete Antwort von {0} (Code {1})"],
        ["avUnavailable"] = ["{0} indisponible ou désactivé (code {1})", "{0} unavailable or disabled (code {1})",
            "{0} no disponible o desactivado (código {1})", "{0} nicht verfügbar oder deaktiviert (Code {1})"],
        ["avDialogTitle"] = ["Vérification antivirus", "Antivirus check", "Comprobación antivirus", "Virenprüfung"],
        ["suspectsHeader"] = ["Suspects", "Suspicious", "Sospechosos", "Verdächtig"],
        ["suspectsSummary"] = ["{0:N0} fichier(s) suspect(s) et {1:N0} à vérifier. Ces fichiers présentent des signes souvent associés aux logiciels malveillants, ce qui n'est pas une preuve : faites-les vérifier par l'antivirus avant toute action.",
            "{0:N0} suspicious file(s) and {1:N0} to check. These files show signs often associated with malware, which is not proof: have them checked by the antivirus before taking any action.",
            "{0:N0} archivo(s) sospechoso(s) y {1:N0} por comprobar. Estos archivos presentan indicios asociados a menudo con software malicioso, lo que no es una prueba: hágalos comprobar con el antivirus antes de actuar.",
            "{0:N0} verdächtige Datei(en) und {1:N0} zu prüfen. Diese Dateien zeigen Anzeichen, die oft mit Schadsoftware verbunden sind – das ist kein Beweis: Lassen Sie sie vor jeder Maßnahme vom Virenschutz prüfen."],
        ["errorsHeader"] = ["Erreurs", "Errors", "Errores", "Fehler"],
        ["topFilesHeader"] = ["Les {0:N0} plus gros fichiers", "The {0:N0} largest files", "Los {0:N0} archivos más grandes", "Die {0:N0} größten Dateien"],
        ["filesTitle"] = ["Fichiers", "Files", "Archivos", "Dateien"],
        ["selectFolder"] = ["Sélectionnez un dossier pour voir ses fichiers.", "Select a folder to see its files.",
            "Seleccione una carpeta para ver sus archivos.", "Wählen Sie einen Ordner aus, um seine Dateien zu sehen."],
        ["loading"] = ["Chargement…", "Loading…", "Cargando…", "Wird geladen…"],
        ["noDirectFiles"] = ["Aucun fichier directement dans ce dossier.", "No files directly in this folder.",
            "No hay archivos directamente en esta carpeta.", "Keine Dateien direkt in diesem Ordner."],
        ["folderFiles"] = ["{0:N0} fichier(s) · {1}", "{0:N0} file(s) · {1}", "{0:N0} archivo(s) · {1}", "{0:N0} Datei(en) · {1}"],
        ["truncated"] = [" (liste tronquée)", " (list truncated)", " (lista truncada)", " (Liste gekürzt)"],
        ["dupIdle"] = ["Lancez la recherche pour trouver les fichiers identiques.", "Start the search to find identical files.",
            "Inicie la búsqueda para encontrar archivos idénticos.", "Starten Sie die Suche, um identische Dateien zu finden."],
        ["dupCandidates"] = ["{0:N0} fichiers de {1} ou plus à comparer.", "{0:N0} files of {1} or more to compare.",
            "{0:N0} archivos de {1} o más para comparar.", "{0:N0} Dateien ab {1} zu vergleichen."],
        ["dupThreshold"] = [" · seuil {0} (fixé lors de l'analyse)", " · threshold {0} (set at scan time)", " · umbral {0} (fijado en el análisis)",
            " · Schwelle {0} (bei der Analyse festgelegt)"],
        ["dupNone"] = ["Aucun doublon trouvé ({0}){1}", "No duplicates found ({0}){1}", "No se encontraron duplicados ({0}){1}", "Keine Duplikate gefunden ({0}){1}"],
        ["dupResult"] = ["{0:N0} groupe(s) · {1:N0} fichiers · {2} récupérables · {3}", "{0:N0} group(s) · {1:N0} files · {2} recoverable · {3}",
            "{0:N0} grupo(s) · {1:N0} archivos · {2} recuperables · {3}", "{0:N0} Gruppe(n) · {1:N0} Dateien · {2} freizugeben · {3}"],
        ["dupUnreadable"] = [" · {0:N0} illisible(s)", " · {0:N0} unreadable", " · {0:N0} ilegible(s)", " · {0:N0} nicht lesbar"],
        ["dupCancelled"] = ["Recherche annulée.", "Search cancelled.", "Búsqueda cancelada.", "Suche abgebrochen."],
        ["dupProgress"] = ["{0} : {1:N0} / {2:N0} fichiers · {3} / {4}", "{0}: {1:N0} / {2:N0} files · {3} / {4}",
            "{0}: {1:N0} / {2:N0} archivos · {3} / {4}", "{0}: {1:N0} / {2:N0} Dateien · {3} / {4}"],
        ["dupStagePartial"] = ["Empreinte partielle", "Partial hash", "Huella parcial", "Teil-Prüfsumme"],
        ["dupStageFull"] = ["Empreinte complète", "Full hash", "Huella completa", "Vollständige Prüfsumme"],
        ["errorPrefix"] = ["Erreur : {0}", "Error: {0}", "Error: {0}", "Fehler: {0}"],
        ["browseTitle"] = ["Dossier à analyser", "Folder to scan", "Carpeta a analizar", "Zu analysierender Ordner"],
        ["scanRunning"] = ["Analyse en cours…", "Scanning…", "Analizando…", "Analyse läuft…"],
        ["volumeInfo"] = ["Volume : {0} utilisés sur {1} ({2:0.0} %) · {3} libres", "Volume: {0} used of {1} ({2:0.0} %) · {3} free",
            "Volumen: {0} usados de {1} ({2:0.0} %) · {3} libres", "Volume: {0} von {1} belegt ({2:0.0} %) · {3} frei"],
        ["volumeShare"] = ["{0:0.0} % du volume de {1}", "{0:0.0} % of the {1} volume", "{0:0.0} % del volumen de {1}", "{0:0.0} % des Volumes von {1}"],
        ["scanDone"] = ["Analyse terminée", "Scan complete", "Análisis terminado", "Analyse abgeschlossen"],
        ["scanPartial"] = ["Analyse interrompue — résultats partiels", "Scan interrupted — partial results", "Análisis interrumpido — resultados parciales",
            "Analyse abgebrochen — Teilergebnisse"],
        ["filesPerSec"] = ["{0:N0} fichiers/s", "{0:N0} files/s", "{0:N0} archivos/s", "{0:N0} Dateien/s"],
        ["scanSuspects"] = [" · ⚠ {0:N0} fichier(s) suspect(s) : voir l'onglet Suspects", " · ⚠ {0:N0} suspicious file(s): see the Suspicious tab",
            " · ⚠ {0:N0} archivo(s) sospechoso(s): ver la pestaña Sospechosos", " · ⚠ {0:N0} verdächtige Datei(en): siehe Registerkarte Verdächtig"],
        ["scanImpossible"] = ["Analyse impossible", "Scan failed", "Análisis imposible", "Analyse nicht möglich"],
        ["exportTitle"] = ["Exporter l'onglet affiché en CSV", "Export the current tab as CSV", "Exportar la pestaña actual en CSV",
            "Aktuelle Registerkarte als CSV exportieren"],
        ["csvFilter"] = ["Fichier CSV (*.csv)|*.csv", "CSV file (*.csv)|*.csv", "Archivo CSV (*.csv)|*.csv", "CSV-Datei (*.csv)|*.csv"],
        ["exporting"] = ["Export en cours…", "Exporting…", "Exportando…", "Export läuft…"],
        ["exported"] = ["Exporté : {0}", "Exported: {0}", "Exportado: {0}", "Exportiert: {0}"],
        ["exportFailed"] = ["Échec de l'export : {0}", "Export failed: {0}", "Error en la exportación: {0}", "Export fehlgeschlagen: {0}"],
        ["staleNone"] = ["Aucun dossier de 1 Mo ou plus sans activité depuis {0} an(s).", "No folder of 1 MB or more without activity for {0} year(s).",
            "Ninguna carpeta de 1 MB o más sin actividad desde hace {0} año(s).", "Kein Ordner ab 1 MB ohne Aktivität seit {0} Jahr(en)."],
        ["staleResult"] = ["{0:N0} dossier(s) sans aucune activité depuis {1} an(s) · {2} · candidats à l'archivage (vérifiez avant de déplacer ou supprimer quoi que ce soit)",
            "{0:N0} folder(s) without any activity for {1} year(s) · {2} · candidates for archiving (check before moving or deleting anything)",
            "{0:N0} carpeta(s) sin ninguna actividad desde hace {1} año(s) · {2} · candidatas a archivar (compruebe antes de mover o eliminar nada)",
            "{0:N0} Ordner ohne jede Aktivität seit {1} Jahr(en) · {2} · Kandidaten für die Archivierung (vor dem Verschieben oder Löschen prüfen)"],
        ["noShares"] = ["Aucun partage accessible sur {0}", "No accessible share on {0}", "Ningún recurso compartido accesible en {0}",
            "Keine zugängliche Freigabe auf {0}"],
        ["folderNotFound"] = ["Dossier introuvable ou inaccessible : {0}", "Folder not found or inaccessible: {0}",
            "Carpeta no encontrada o inaccesible: {0}", "Ordner nicht gefunden oder nicht zugänglich: {0}"],
        ["sharesFailed"] = ["Impossible de lister les partages de {0} (code {1}).", "Unable to list the shares of {0} (code {1}).",
            "No se pueden enumerar los recursos compartidos de {0} (código {1}).", "Die Freigaben von {0} können nicht aufgelistet werden (Code {1})."],
        ["searchNone"] = ["Aucun dossier trouvé", "No folder found", "No se encontró ninguna carpeta", "Kein Ordner gefunden"],
        ["notInstalled"] = [" (non installé)", " (not installed)", " (no instalado)", " (nicht installiert)"],
        ["unexpectedError"] = ["Erreur inattendue", "Unexpected error", "Error inesperado", "Unerwarteter Fehler"],
        ["explorer"] = ["Explorateur", "File Explorer", "Explorador", "Explorer"],
        ["propertiesFailed"] = ["Impossible d'afficher les propriétés de cet élément.", "Unable to show the properties of this item.",
            "No se pueden mostrar las propiedades de este elemento.", "Die Eigenschaften dieses Elements können nicht angezeigt werden."],

        // ---- Exports CSV (noms de fichiers et colonnes) ----
        ["csvTree"] = ["arborescence", "tree", "arbol", "verzeichnisbaum"],
        ["csvBig"] = ["gros-fichiers", "largest-files", "archivos-grandes", "groesste-dateien"],
        ["csvTypes"] = ["types-de-fichiers", "file-types", "tipos-de-archivo", "dateitypen"],
        ["csvDup"] = ["doublons", "duplicates", "duplicados", "duplikate"],
        ["csvSuspects"] = ["fichiers-suspects", "suspicious-files", "archivos-sospechosos", "verdaechtige-dateien"],
        ["csvErrors"] = ["erreurs", "errors", "errores", "fehler"],
        ["csvStale"] = ["dossiers-inactifs", "inactive-folders", "carpetas-inactivas", "inaktive-ordner"],
        ["colDepth"] = ["Profondeur", "Depth", "Profundidad", "Tiefe"],
        ["colBytes"] = ["Taille (octets)", "Size (bytes)", "Tamaño (bytes)", "Größe (Bytes)"],
        ["colSubfolders"] = ["Sous-dossiers", "Subfolders", "Subcarpetas", "Unterordner"],
        ["colDirectFiles"] = ["Fichiers directs", "Direct files", "Archivos directos", "Direkte Dateien"],
        ["colDirectBytes"] = ["Taille fichiers directs (octets)", "Direct files size (bytes)", "Tamaño archivos directos (bytes)", "Größe direkter Dateien (Bytes)"],
        ["colNewest"] = ["Dernière modif. contenu", "Content last modified", "Última modif. del contenido", "Inhalt zuletzt geändert"],
        ["colLink"] = ["Lien/Jonction", "Link/Junction", "Vínculo/Unión", "Link/Verbindungspunkt"],
        ["colModified"] = ["Dernière modif.", "Last modified", "Última modif.", "Zuletzt geändert"],
        ["colPctTotal"] = ["% total", "% total", "% total", "% gesamt"],
        ["colAvgBytes"] = ["Taille moyenne (octets)", "Average size (bytes)", "Tamaño medio (bytes)", "Durchschnittsgröße (Bytes)"],
        ["colGroup"] = ["Groupe", "Group", "Grupo", "Gruppe"],
        ["colRecoverableBytes"] = ["Espace récupérable (octets)", "Recoverable space (bytes)", "Espacio recuperable (bytes)", "Freizugebender Speicher (Bytes)"],
        ["colReasons"] = ["Raisons", "Reasons", "Motivos", "Gründe"],
        ["colAvCheck"] = ["Vérification antivirus", "Antivirus check", "Comprobación antivirus", "Virenprüfung"],
        ["yes"] = ["oui", "yes", "sí", "ja"],
        ["noExtension"] = ["(sans extension)", "(no extension)", "(sin extensión)", "(ohne Erweiterung)"],

        // ---- Indices de suspicion ----
        ["levelDanger"] = ["Suspect", "Suspicious", "Sospechoso", "Verdächtig"],
        ["levelWarning"] = ["À vérifier", "To check", "Por comprobar", "Zu prüfen"],
        ["suspicionTip"] = ["⚠ ATTENTION — {0} : {1}", "⚠ WARNING — {0}: {1}", "⚠ ATENCIÓN — {0}: {1}", "⚠ ACHTUNG — {0}: {1}"],
        ["rHidden"] = ["caractères invisibles qui inversent l'affichage du nom (vraie extension masquée)",
            "invisible characters that reverse how the name is displayed (real extension hidden)",
            "caracteres invisibles que invierten la visualización del nombre (extensión real oculta)",
            "unsichtbare Zeichen, die die Anzeige des Namens umkehren (echte Erweiterung verborgen)"],
        ["rDouble"] = ["double extension : se fait passer pour un document alors que c'est un programme",
            "double extension: poses as a document but is actually a program",
            "doble extensión: se hace pasar por un documento cuando es un programa",
            "doppelte Erweiterung: gibt sich als Dokument aus, ist aber ein Programm"],
        ["rRansomExt"] = ["extension typique d'un fichier chiffré par un rançongiciel", "extension typical of a file encrypted by ransomware",
            "extensión típica de un archivo cifrado por ransomware", "typische Erweiterung einer von Ransomware verschlüsselten Datei"],
        ["rRansomNote"] = ["ressemble à une demande de rançon", "looks like a ransom note", "parece una nota de rescate", "sieht wie eine Lösegeldforderung aus"],
        ["rImpersonation"] = ["porte le nom d'un programme de Windows mais se trouve hors du dossier Windows",
            "has the name of a Windows program but is outside the Windows folder",
            "tiene el nombre de un programa de Windows pero está fuera de la carpeta de Windows",
            "trägt den Namen eines Windows-Programms, liegt aber außerhalb des Windows-Ordners"],
        ["rRiskyType"] = ["type de fichier souvent utilisé par les virus (script / économiseur d'écran)",
            "file type often used by viruses (script / screen saver)", "tipo de archivo usado a menudo por virus (script / protector de pantalla)",
            "Dateityp, der oft von Viren verwendet wird (Skript / Bildschirmschoner)"],
        ["rRiskyLocation"] = ["situé dans un dossier à risque (Temp, Téléchargements, Corbeille, Public, Démarrage)",
            "located in a risky folder (Temp, Downloads, Recycle Bin, Public, Startup)",
            "ubicado en una carpeta de riesgo (Temp, Descargas, Papelera, Público, Inicio)",
            "befindet sich in einem riskanten Ordner (Temp, Downloads, Papierkorb, Öffentlich, Autostart)"],
        ["rStartup"] = ["se lance automatiquement au démarrage de Windows", "starts automatically when Windows starts",
            "se inicia automáticamente al arrancar Windows", "startet automatisch mit Windows"],
        ["rHiddenExe"] = ["programme caché hors des dossiers d'applications", "hidden program outside application folders",
            "programa oculto fuera de las carpetas de aplicaciones", "verstecktes Programm außerhalb der Anwendungsordner"],
        ["rSystemAttr"] = ["programme marqué « fichier système » hors du dossier Windows (camouflage)",
            "program marked as a \"system file\" outside the Windows folder (camouflage)",
            "programa marcado como «archivo de sistema» fuera de la carpeta de Windows (camuflaje)",
            "Programm als „Systemdatei“ markiert außerhalb des Windows-Ordners (Tarnung)"],
        ["rAmbiguous"] = ["nom piégé (point ou espace final, nom réservé) : Windows le confond avec un autre fichier",
            "booby-trapped name (trailing dot or space, reserved name): Windows confuses it with another file",
            "nombre trampa (punto o espacio final, nombre reservado): Windows lo confunde con otro archivo",
            "manipulierter Name (Punkt oder Leerzeichen am Ende, reservierter Name): Windows verwechselt ihn mit einer anderen Datei"],
        ["safetyCritical"] = ["Ne pas supprimer : élément indispensable au fonctionnement de Windows ou des applications",
            "Do not delete: essential for Windows or applications to work",
            "No eliminar: elemento imprescindible para el funcionamiento de Windows o de las aplicaciones",
            "Nicht löschen: für Windows oder Anwendungen unverzichtbar"],
        ["safetySystem"] = ["Élément système Windows : à ne modifier qu'en connaissance de cause", "Windows system item: only change it if you know what you are doing",
            "Elemento del sistema Windows: modifíquelo solo si sabe lo que hace", "Windows-Systemelement: nur mit entsprechendem Fachwissen ändern"],

        // ---- Installation ----
        ["installTitle"] = ["PrimaFiles — installation", "PrimaFiles — setup", "PrimaFiles — instalación", "PrimaFiles — Installation"],
        ["uninstallTitle"] = ["PrimaFiles — désinstallation", "PrimaFiles — uninstall", "PrimaFiles — desinstalación", "PrimaFiles — Deinstallation"],
        ["installAsk"] = ["Installer PrimaFiles sur cet ordinateur ?\n\n•  Copie dans C:\\Program Files\\PrimaFiles (dossier protégé)\n•  Raccourci dans le menu Démarrer\n•  Plus d'alerte de Windows au lancement\n•  Désinstallation depuis Paramètres > Applications\n\nOui : installer (droits administrateur demandés)\nNon : utiliser sans installer",
            "Install PrimaFiles on this computer?\n\n•  Copied to C:\\Program Files\\PrimaFiles (protected folder)\n•  Start menu shortcut\n•  No more Windows warning at launch\n•  Uninstall from Settings > Apps\n\nYes: install (administrator rights required)\nNo: use without installing",
            "¿Instalar PrimaFiles en este equipo?\n\n•  Copia en C:\\Program Files\\PrimaFiles (carpeta protegida)\n•  Acceso directo en el menú Inicio\n•  Sin más avisos de Windows al iniciar\n•  Desinstalación desde Configuración > Aplicaciones\n\nSí: instalar (se requieren derechos de administrador)\nNo: usar sin instalar",
            "PrimaFiles auf diesem Computer installieren?\n\n•  Kopie nach C:\\Program Files\\PrimaFiles (geschützter Ordner)\n•  Verknüpfung im Startmenü\n•  Keine Windows-Warnung mehr beim Start\n•  Deinstallation über Einstellungen > Apps\n\nJa: installieren (Administratorrechte erforderlich)\nNein: ohne Installation verwenden"],
        ["updateAsk"] = ["La version {0} de PrimaFiles est installée.\n\nMettre à jour l'installation vers la version {1} ?",
            "PrimaFiles version {0} is installed.\n\nUpdate the installation to version {1}?",
            "La versión {0} de PrimaFiles está instalada.\n\n¿Actualizar la instalación a la versión {1}?",
            "PrimaFiles Version {0} ist installiert.\n\nInstallation auf Version {1} aktualisieren?"],
        ["installCancelled"] = ["Installation annulée : PrimaFiles va s'ouvrir sans être installé.", "Setup cancelled: PrimaFiles will open without being installed.",
            "Instalación cancelada: PrimaFiles se abrirá sin instalarse.", "Installation abgebrochen: PrimaFiles wird ohne Installation geöffnet."],
        ["installedFull"] = ["PrimaFiles {0} est installé dans {1}.\n\nIl est disponible dans le menu Démarrer. Vous pouvez supprimer le fichier téléchargé.",
            "PrimaFiles {0} is installed in {1}.\n\nIt is available in the Start menu. You can delete the downloaded file.",
            "PrimaFiles {0} está instalado en {1}.\n\nEstá disponible en el menú Inicio. Puede eliminar el archivo descargado.",
            "PrimaFiles {0} ist in {1} installiert.\n\nEs ist im Startmenü verfügbar. Sie können die heruntergeladene Datei löschen."],
        ["installedShort"] = ["PrimaFiles est installé dans {0}.", "PrimaFiles is installed in {0}.", "PrimaFiles está instalado en {0}.", "PrimaFiles ist in {0} installiert."],
        ["installFailed"] = ["Installation impossible : {0}", "Setup failed: {0}", "Instalación imposible: {0}", "Installation nicht möglich: {0}"],
        ["uninstallAsk"] = ["Désinstaller PrimaFiles ?\n\nVos réglages (historique, thème) sont conservés.", "Uninstall PrimaFiles?\n\nYour settings (history, theme) are kept.",
            "¿Desinstalar PrimaFiles?\n\nSe conservan sus ajustes (historial, tema).", "PrimaFiles deinstallieren?\n\nIhre Einstellungen (Verlauf, Design) bleiben erhalten."],
        ["uninstalled"] = ["PrimaFiles a été désinstallé.", "PrimaFiles has been uninstalled.", "PrimaFiles se ha desinstalado.", "PrimaFiles wurde deinstalliert."],
        ["uninstallFailed"] = ["Désinstallation impossible : {0}", "Uninstall failed: {0}", "Desinstalación imposible: {0}", "Deinstallation nicht möglich: {0}"],
        ["explorerVerb"] = ["Analyser avec PrimaFiles", "Scan with PrimaFiles", "Analizar con PrimaFiles", "Mit PrimaFiles analysieren"],
        ["shortcutDescription"] = ["Analyse de l'espace disque et des partages réseau", "Disk space and network share analyzer",
            "Análisis del espacio en disco y de los recursos de red", "Analyse von Speicherplatz und Netzwerkfreigaben"],
    };

    /// <summary>Unités de taille : « Ko, Mo, Go » en français, « KB, MB, GB » ailleurs.</summary>
    public static string[] ByteUnits => Instance._index == 0 ? FrUnits : IntlUnits;
    public static string ByteUnit => Instance._index == 0 ? "o" : "B";
    private static readonly string[] FrUnits = ["Ko", "Mo", "Go", "To", "Po"];
    private static readonly string[] IntlUnits = ["KB", "MB", "GB", "TB", "PB"];
}
